/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_media_protocol_screen_NativeCapture */

#ifndef _Included_com_googlecode_vicovre_media_protocol_screen_NativeCapture
#define _Included_com_googlecode_vicovre_media_protocol_screen_NativeCapture
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_vicovre_media_protocol_screen_NativeCapture
 * Method:    init
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_media_protocol_screen_NativeCapture_init
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     com_googlecode_vicovre_media_protocol_screen_NativeCapture
 * Method:    captureScreen
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_media_protocol_screen_NativeCapture_captureScreen
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_googlecode_vicovre_media_protocol_screen_NativeCapture
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_media_protocol_screen_NativeCapture_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
