/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec */

#ifndef _Included_com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec
#define _Included_com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec
 * Method:    openCodec
 * Signature: (IIIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec_openCodec
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec
 * Method:    process
 * Signature: (JLjavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec_process
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec
 * Method:    closeCodec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_SWScaleCodec_closeCodec
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
