/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec */

#ifndef _Included_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
#define _Included_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: SYNC */
/* Inaccessible static: CODECS */
/* Inaccessible static: INPUT_FORMATS */
/* Inaccessible static: OUTPUT_FORMATS */
/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
 * Method:    openCodec
 * Signature: (ZI)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec_openCodec
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
 * Method:    init
 * Signature: (IIIIIIZLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint, jboolean, jstring);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
 * Method:    decodeNative
 * Signature: (Ljavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec_decodeNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
 * Method:    encodeNative
 * Signature: (Ljavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec_encodeNative
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec
 * Method:    closeCodec
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_FFMPEGCodec_closeCodec
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
