/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer */

#ifndef _Included_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
#define _Included_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: CONTENT_TYPES */
/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    init
 * Signature: (Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_init
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getNoStreams
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getNoStreams
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getCodecName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getCodecName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getCodecType
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getCodecType
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getOutputSize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getOutputSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getSourceDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getSourceDuration
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getStreamDuration
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getStreamDuration
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getStartTime
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getStartTime
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    setStreamOutputVideoFormat
 * Signature: (JIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_setStreamOutputVideoFormat
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getVideoWidth
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getVideoWidth
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getVideoHeight
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getVideoHeight
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getVideoPixelFormat
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getVideoPixelFormat
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getVideoFrameRate
 * Signature: (JI)D
 */
JNIEXPORT jdouble JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getVideoFrameRate
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    setStreamAudioDecoded
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_setStreamAudioDecoded
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getAudioSampleSize
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getAudioSampleSize
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getNoAudioChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getNoAudioChannels
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    getAudioSampleRate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_getAudioSampleRate
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    readNextFrame
 * Signature: (JLjavax/media/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_readNextFrame
  (JNIEnv *, jobject, jlong, jobject, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    seek
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_seek
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer
 * Method:    dispose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_demuxer_FFMPEGDemuxer_dispose
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
