/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec */

#ifndef _Included_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
#define _Included_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    open
 * Signature: (ZII)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_open
  (JNIEnv *, jobject, jboolean, jint, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    fillInCodecContext
 * Signature: (JLcom/googlecode/vicovre/codecs/ffmpeg/audio/AudioCodecContext;)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_fillInCodecContext
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    init
 * Signature: (JLcom/googlecode/vicovre/codecs/ffmpeg/audio/AudioCodecContext;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_init
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    encode
 * Signature: (JLjavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_encode
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    decode
 * Signature: (JLjavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_decode
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_ffmpeg_audio_FFMPEGAudioCodec_close
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
