/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_vic_NativeDecoder */

#ifndef _Included_com_googlecode_vicovre_codecs_vic_NativeDecoder
#define _Included_com_googlecode_vicovre_codecs_vic_NativeDecoder
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: CODECS */
/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeDecoder
 * Method:    openCodec
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeDecoder_openCodec
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeDecoder
 * Method:    decodeHeader
 * Signature: (JLjavax/media/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeDecoder_decodeHeader
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeDecoder
 * Method:    decode
 * Signature: (JLjavax/media/Buffer;Ljavax/media/Buffer;)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeDecoder_decode
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeDecoder
 * Method:    closeCodec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeDecoder_closeCodec
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
