/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_googlecode_vicovre_codecs_vic_NativeEncoder */

#ifndef _Included_com_googlecode_vicovre_codecs_vic_NativeEncoder
#define _Included_com_googlecode_vicovre_codecs_vic_NativeEncoder
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: CODECS */
/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeEncoder
 * Method:    openCodec
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeEncoder_openCodec
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeEncoder
 * Method:    setSize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeEncoder_setSize
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeEncoder
 * Method:    encode
 * Signature: (JLjavax/media/Buffer;Ljavax/media/Buffer;[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeEncoder_encode
  (JNIEnv *, jobject, jlong, jobject, jobject, jintArray, jintArray);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeEncoder
 * Method:    keyFrame
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeEncoder_keyFrame
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_googlecode_vicovre_codecs_vic_NativeEncoder
 * Method:    closeCodec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_googlecode_vicovre_codecs_vic_NativeEncoder_closeCodec
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
